### ISSUE TITLE
cephadm: CEPHADM_STRAY_DAEMON: bootstrap mgr not managed by ceph

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph-salt#135]
<pre>
# ceph -s
  cluster:
    id:     6cf878a8-6dbb-11ea-81f8-fa163e09adda
    health: HEALTH_WARN
            1 stray daemons(s) not managed by cephadm
 
  services:
    mon: 1 daemons, quorum host1 (age 12m)
    mgr: host1.rpcqxx(active, since 11m), standbys: host4.xgjlhi, host2.lnnfdk
    osd: 12 osds: 12 up (since 6m), 12 in (since 6m)
 
  data:
    pools:   1 pools, 1 pgs
    objects: 0 objects, 0 B
    usage:   12 GiB used, 108 GiB / 120 GiB avail
    pgs:     1 active+clean
 
# ceph health detail
HEALTH_WARN 1 stray daemons(s) not managed by cephadm
[WRN] CEPHADM_STRAY_DAEMON: 1 stray daemons(s) not managed by cephadm
    stray daemon mgr.host1.rpcqxx on host host1 not managed by cephadm
</pre>

<pre>
# ceph orch ps
NAME              HOST   STATUS         REFRESHED  AGE  VERSION  IMAGE NAME        IMAGE ID      CONTAINER ID  
mgr.host2.lnnfdk  host2  running (19m)  4m ago     19m  15.2.0   ceph/ceph:latest  4947e2bbb809  4257d130525e  
mgr.host4.xgjlhi  host4  running (19m)  4m ago     19m  15.2.0   ceph/ceph:latest  4947e2bbb809  9d9a9f6965ad  
mon.host1         host1  running (21m)  4m ago     -    15.2.0   ceph/ceph:latest  4947e2bbb809  614e444780ff  
osd.0             host1  running (18m)  4m ago     18m  15.2.0   ceph/ceph:latest  4947e2bbb809  1a363bd5f838  
osd.1             host1  running (18m)  4m ago     18m  15.2.0   ceph/ceph:latest  4947e2bbb809  87ba39c1378e  
osd.10            host2  running (15m)  4m ago     15m  15.2.0   ceph/ceph:latest  4947e2bbb809  0fc086350f3b  
osd.11            host2  running (15m)  4m ago     15m  15.2.0   ceph/ceph:latest  4947e2bbb809  9703a260c81f  
osd.2             host1  running (17m)  4m ago     17m  15.2.0   ceph/ceph:latest  4947e2bbb809  787580630f41  
osd.3             host1  running (17m)  4m ago     17m  15.2.0   ceph/ceph:latest  4947e2bbb809  86de0c4154dd  
osd.4             host4  running (16m)  4m ago     16m  15.2.0   ceph/ceph:latest  4947e2bbb809  5c721a415f36  
osd.5             host4  running (16m)  4m ago     16m  15.2.0   ceph/ceph:latest  4947e2bbb809  c8973fe56f35  
osd.6             host4  running (16m)  4m ago     16m  15.2.0   ceph/ceph:latest  4947e2bbb809  15feeeda2f01  
osd.7             host4  running (16m)  4m ago     16m  15.2.0   ceph/ceph:latest  4947e2bbb809  0bcfd8d6231a  
osd.8             host2  running (15m)  4m ago     15m  15.2.0   ceph/ceph:latest  4947e2bbb809  4d14b7d89bf2  
osd.9             host2  running (15m)  4m ago     15m  15.2.0   ceph/ceph:latest  4947e2bbb809  4c3820fe459b  
</pre>

```yaml
# ceph orch host ls  --format yaml
- addr: target-GeKy-mainstream-004
  hostname: target-GeKy-mainstream-004
  labels: []
  status: ''
- addr: host4
  hostname: host4
  labels: []
  status: ''
- addr: host1
  hostname: host1
  labels: []
  status: ''
- addr: host2
  hostname: host2
  labels: []
  status: ''
```

placement misses the bootstrap minion:
```yaml
# ceph orch ls --service_type=mgr --format yaml
- container_image_id: 4947e2bbb809c3bc2a5d32e161bac53adaaf035c39376b9c87c42dc90cbec244
  container_image_name: ceph/ceph:latest
  created: '2020-03-24T10:38:53.165954'
  last_refresh: '2020-03-24T10:53:50.447580'
  running: 2
  service_name: mgr
  size: 2
  spec:
    placement:
      hosts:
      - hostname: host4
        name: ''
        network: ''
      - hostname: host2
        name: ''
        network: ''
    service_type: mgr
```
