### ISSUE TITLE
Store minion_id in pillar instead of hostname

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#210]
ATM, we are storing `short_name`s in pillar

```
ceph-salt:
  bootstrap_minion: node1.octopus-reboot.com
...
  minions:
    admin:
    - node1
    - node2
    - node3
    - master
    all:
    - node1
    - node2
    - node3
    - master
```

`ceph-salt` should always store `minion_ids` and only calculate the short name when needed  https://github.com/ceph/ceph-salt/blob/3eb6982e47d9a8b458b72d50c5be898deba24301/ceph_salt/core.py#L22
