### ISSUE TITLE
deployment fails on `wait for time server sync`

### ISSUE THREAD

**Issue by bk201** [ceph/ceph-salt#238]
ceph-salt deployment fails when waiting for time server sync
```
Failure in minion: master.ses7.com
__id__: run sync script
__run_num__: 43
__sls__: ceph-salt.time-sync
changes:
  pid: 14090
  retcode: 1
  stderr: ''
  stdout: 503 No such source
comment: 'Command "/tmp/chrony_sync_clock.sh
```
If I tried `ceph-salt -ldebug apply --non-interactive` again, the time syncing **will succeed**. It only happens on first attemp.

Other information:
```
version: ceph-salt 15.2.4+1589550818.gaf48859


    master:   o- time_server ......................................................................................................... [enabled]
    master:     o- external_servers ........................................................................................................ [1]
    master:     | o- pool.ntp.org ........................................................................................................ [...]
    master:     o- server_hostname ........................................................................................... [master.ses7.com]
    master:     o- subnet ...................................................................................................... [10.20.53.0/24]

```
Log file: 
[time_sync_error.log](https://github.com/ceph/ceph-salt/files/4644620/time_sync_error.log)
