### ISSUE TITLE
ceph-salt appears to be broken on Tumbleweed

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#375]
Reproducer:

```
sesdev --verbose create pacific --os tumbleweed --non-interactive
```

Fails with:

```
    master: 4 of 4 minions responded to ping.
    master: PATH is /usr/sbin:/usr/bin:/sbin:/bin
    master: ceph-salt is /usr/bin/ceph-salt
    master: ++ echo 'PATH is /usr/sbin:/usr/bin:/sbin:/bin'
    master: ++ type ceph-salt
    master: ++ ceph-salt config /ceph_cluster/minions add master.pacific.test
    master: Traceback (most recent call last):
    master:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    master:     ws.require(__requires__)
    master:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    master:     needed = self.resolve(parse_requirements(requirements))
    master:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    master:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    master:     f(*args, **kwargs)
    master:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    master:     working_set = WorkingSet._build_master()
    master:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    master:     return cls._build_from_requirements(__requires__)
    master:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    master:     dists = ws.resolve(reqs, Environment())
    master:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    master:     raise DistributionNotFound(req, requirers)
    master: pkg_resources.DistributionNotFound: The 'msgpack!=0.5.5,<1.0.0,>=0.5' distribution was not found and is required by salt
```

**Comment by smithfarm** [comment]
I gleaned some further bits of information:

1. pipdeptree shows where the `msgpack!=0.5.5,<1.0.0,>=0.5` requirement is coming from:

```
...
  - salt [required: >=3000, installed: 3000.3]
    - Jinja2 [required: Any, installed: 2.11.2]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - MarkupSafe [required: Any, installed: 1.1.1]
    - msgpack [required: >=0.5,<1.0.0,!=0.5.5, installed: 0.6.2]
...
```

2. the failure only happens when ceph-salt is installed from RPM, because (on Tumbleweed):

```
master:~/ceph-salt # rpm -q python3-msgpack
python3-msgpack-1.0.0-1.4.x86_64
```

(1.0.0 does not satisfy the version restriction `!=0.5.5,<1.0.0,>=0.5`)

So this appears to be a salt packaging bug. To report the bug, I'll probably need a minimal reproducer.

**Comment by smithfarm** [comment]
This appears to be a packaging bug in salt. I opened a Bugzilla:

https://bugzilla.opensuse.org/show_bug.cgi?id=1176293

**Comment by ricardoasmarques** [comment]
It's working now:

```
# sesdev --verbose create pacific --os tumbleweed --non-interactive
...

# sesdev ssh pacific                                                                                                                                                                           rimarques@linux-o898
Have a lot of fun...
master:~ # ceph -s
  cluster:
    id:     8a558786-fde6-11ea-a01e-525400ffde33
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum node1,node2,node3 (age 6m)
    mgr: node1.shndgz(active, since 4m), standbys: node3.xljqle, node2.kuexoj
    mds: sesdev_fs:1 {0=sesdev_fs.node2.pwwpyy=up:active} 1 up:standby
    osd: 6 osds: 6 up (since 5m), 6 in (since 5m)
    rgw: 2 daemons active (default.default.node1.yigbve, default.default.node3.ijvthm)
 
  data:
    pools:   9 pools, 233 pgs
    objects: 351 objects, 28 KiB
    usage:   97 MiB used, 48 GiB / 48 GiB avail
    pgs:     0.429% pgs not active
             232 active+clean
             1   peering
 
  io:
    client:   2.3 KiB/s rd, 2 op/s rd, 0 op/s wr
 
  progress:
    PG autoscaler decreasing pool 9 PGs from 32 to 8 (3m)
      [==========================..] (remaining: 7s)
```
