### ISSUE TITLE
Error deploying config without external time server

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#40]
When deploying the following configuration, without external time server:

```
  o- Time_Server ................................................................. [enabled]
    o- External_Servers ............................................................ [empty]
    o- Server_Hostname ................................................. [node1.octopus.com]
```

I'm getting the following error:

```
----------
          ID: /etc/chrony.conf
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'dict object' has no attribute 'external_time_servers'
     Started: 10:37:14.223639
    Duration: 47.736 ms
     Changes:   
----------
```

To fix this, we should check if any external time server was configured before setting it up.
