### ISSUE TITLE
Update ceph-salt pillar example

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#434]
When `ceph-salt-formula` is installed, a `pillar.example` file is created, but this example is outdated/incomplete so it needs to be updated:
```
master:~ # cat /usr/share/salt-formulas/metadata/ceph-salt/pillar.example 
ceph-salt:
  minions:
    - <minion_id_1>
    - <minion_id_1>
    # ...
  bootstrap_minion: <bootstrap_minion_id>
  ssh:
    private_key: |
      <key_data_line1>
      <key_data_line2>
      # ...

    public_key: <key_data>
  time_server:
    enabled: True
    host_server: <minion id of admin node>
    external_time_servers:
      - <server1>
      - <server2>
      # ...
```
